In [24]:
#NAME-S.MANOJ
#REG NO-20BEC1213

In [25]:
#1
Name="MANOJ"
print(Name)

MANOJ


In [26]:
Age=21
print(Age)

21


In [27]:
#2
X="Datascience is used to extract meaningful insights."
s=X.split(" ")
s

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']

In [28]:
#3
def mult(a,b):
    return a*b
mult(2,9)

18

In [29]:
states={"TamilNadu":"Chennai","Karnataka":"Banglore","Telangana":"Hyderabad","Rajasthan":"Jaipur","UttarPradesh":"Lucknow"}
states

{'TamilNadu': 'Chennai',
 'Karnataka': 'Banglore',
 'Telangana': 'Hyderabad',
 'Rajasthan': 'Jaipur',
 'UttarPradesh': 'Lucknow'}

In [30]:
#5
l=list(range(0,1001))

In [31]:
import numpy as np

In [32]:
#6
m=np.identity(4)

In [33]:
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
#7
n=np.arange(1,10).reshape(3,3)

In [35]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
#8
a=np.array([[9,11,8],[4,2,1],[9,5,1]])
b=np.array([[2,1,0],[1,5,2],[7,2,0]])
c=a+b
print(c)

[[11 12  8]
 [ 5  7  3]
 [16  7  1]]


In [37]:
import datetime
import pandas as pd



In [38]:
#9
test_date = datetime.datetime.strptime("01-2-2023", "%d-%m-%Y")
K = 28
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))



Index(['01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023', '05-02-2023',
       '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023', '10-02-2023',
       '11-02-2023', '12-02-2023', '13-02-2023', '14-02-2023', '15-02-2023',
       '16-02-2023', '17-02-2023', '18-02-2023', '19-02-2023', '20-02-2023',
       '21-02-2023', '22-02-2023', '23-02-2023', '24-02-2023', '25-02-2023',
       '26-02-2023', '27-02-2023', '28-02-2023'],
      dtype='object')


In [39]:
#10
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
d=pd.DataFrame.from_dict(dictionary)
d

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240